### ISSUE TITLE
Add dynamic locale functionality

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-operations#101]
This issue will track the commits that convert NLO to support dynamic locale using dynamic layout

**Comment by amanda-phet** [comment]
Discussed with @marlitas and we'll make the tags on the positive/negative and asset/debt bags the same for each screen, even though the words are different lengths, because the string lengths vary quite a bit between locales and it seems nice to just provide more room so fewer languages will need to shrink the text down.

**Comment by amanda-phet** [comment]
Everything else was looking pretty good to me! QA will be more thorough but I tried to look through as much as I could think of.

**Comment by marlitas** [comment]
Great! I believe this issue can now be closed.
