### ISSUE TITLE
small issues seen with total amount in money bag when locale is changed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#106]
**Test device**
MacBook Air M1 chip/iPad

**Operating System**
MacOS14.1.1/iPadOS 17.0.2

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/1007 on the Chips Screen:
These are minor issues but with some fonts the total isn't centered:

<img width="260" alt="Screenshot 2023-12-04 at 4 43 42 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/21627ada-b01d-416f-a638-9c9453b46df6">

Also, with stringTest=dynamic, the text can exceed the size of the money bag:
<img width="101" alt="Screenshot 2023-12-04 at 4 37 35 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/dcfbea7d-6c51-4435-8de1-ef73a0b9b491">

**Comment by marlitas** [comment]
It looks like the Greek is not centered because there's a space after the translation? 

<img width="176" alt="image" src="https://github.com/phetsims/number-line-operations/assets/42476338/e7ba2d4d-ee33-4e0c-a952-8c5551618c46">

The Text object itself is centered, so I'm not sure that's something I can fix.

I went ahead and committed a solution for the maxWidth of the money bag label. It required some bigger changes and typescript conversion so I would like a review from @AgustinVallejo or @Luisav1 before closing.

@Nancy-Salpepi can you check its looking good on main?

**Comment by marlitas** [comment]
Okay that's been fixed above. Closing!
