### ISSUE TITLE
Operations screen: remove dynamic description when user clicks away

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#23]
We'd like this description to disappear if the user interacts somewhere other than the operation control, or just clicks away. 

![image](https://user-images.githubusercontent.com/7852916/99006910-6cc4da00-2500-11eb-9468-fb15b15d3290.png)

**Comment by amanda-phet** [comment]
Just had a thought. If we remove auto-scrolling (#22 ) do we still need to make this change? I suppose we do if someone uses the control and never click the blue button.. we want that text gone.

**Comment by jbphet** [comment]
The version shown in today's design meeting was good except that we want to make sure that the description does not appear when the number-line-erase button is pressed, which it currently does.  This can be done by making a blanket rule that the dynamic operations are *only* shown when changes to and operation occur due to interaction with the operation entry carousel, and the design team agrees that this is a good approach (at least for now).

**Comment by jbphet** [comment]
The behavior has been updated based on my best understanding of what we're after with this.  @amanda-phet, @kathy-phet, and I also discussed a slight change to the behavior while switching between carousel pages today.

@amanda-phet - assigning to you for review.  If you're good with it, please unassign and mark as "ready-for-qa".  I'd like the QA team to verify this one during the RC testing since the behavior is a bit complex.

**Comment by amanda-phet** [comment]
Seems to be working great!

**Comment by KatieWoe** [comment]
Things look good in dev.13. Will reopen if something comes up.
