### ISSUE TITLE
dependency on number-line-distance

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#37]
Related to #35 code review.

package.json lists these dependencies:

```
    "phetLibs": [
      "number-line-common",
      "twixt",
      "number-line-distance"
    ],
```

When a family of sims has a common repo like `number-line-common`, why is it also dependent on another sim in the family -- in this case `number-line-distance`?   If there's code that is shared with `number-line-distance`, should that code be moved to `number-line-common`?

**Comment by pixelzoom** [comment]
implementation-notes.md also confirms that code-sharing is via number-line-common, not by reaching into other sims in the "suite":

> Also, this simulation is part of the "Number Line Suite" of sims, and as such shares code with the other sims in the suite through the number-line-common repository.

**Comment by jbphet** [comment]
This was added by @jonathanolson in 599c54fc46a0da481b3b20ace57b2664382f6914 because number-line-distance was identified by an automated tool as a dependency of this sim.  That happened because a file that had been moved into common code had incorrectly used the namespace from number-line-distance.  I think it should be straightened out now.

I'll leave this open for a day or so to make sure that nothing pops up on CT, and if all looks good I'll close.

**Comment by jbphet** [comment]
By the way, this problem also afflicted number-line-integers, so I fixed it there as well.

**Comment by jbphet** [comment]
CT looks good, closing.
