### ISSUE TITLE
Usability of "Simplify" and "=" buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#41]
Noted during #35 code review.

When expanded, the Net Worth (Operations screen) and Numerical Expression (Generic screen) accordion boxes look like the screenshot below.  You've probably discussed these already, but I thought I'd note a couple of potential usability problems:

(1) I never did figure out how to make the "Simplify" button become enabled. Maybe I'll discover how this works when reviewing the code. And hopefully the students are smarter than me :)

(2) It took me several presses to realize that the "=" button is a momentary button, not a push button.

<img width="360" alt="screenshot_788" src="https://user-images.githubusercontent.com/3046552/103158044-c878b900-4776-11eb-9986-dad0ff2c1053.png">

**Comment by amanda-phet** [comment]
(1) We originally had a checkbox, but unless there is a situation to simplify (which isn't too common: it's when there is a sequence such as 5 +-2, it simplifies it to 5–2), the checkbox did "nothing." In interviews that was a common question from students, so this way, students will understand what it does better because when they click it, it will actually "do" something.

(2) Do you have a suggestion for another component? We don't want a checkbox or something that can permanently change the appearance of the expression. But we want a way to connect -4 + 0 + 7 to the sum, 3. Students also pressed it a few times before realizing they had to hold it, but they did all figure it out.

**Comment by pixelzoom** [comment]
(1) I understand (and agree with) keeping the button enabled when it doesn't do anything.  But the button never did become enabled for me, and that was a little frustrating.  And I have no idea what "Simplify" even means -- does it mean combine all of the negative and positive terms, like "-4 + -2 + 7 + 2" -> "-6 + 9"?  Maybe it's obvious and I just didn't get it.  But can you describe a scenario where it becomes enabled?  

(2) Sorry, I don't have a suggestion.

**Comment by pixelzoom** [comment]
(1) OK, I finally got the "Simplify" button to become enabled.  It happens in a case like "-200 - 100 - -100" -> "-200 - 100 + 100".   So it adjusts operators and operands so you don't have "- -".    That is definitely not the definition of simplfication for a numeric expression (eg https://www.math-only-math.com/simplification-of-numerical-expressions.html), which is what I was expecting from the use of "Simplify".   You might consider some other word, especially in a math sim.

**Comment by amanda-phet** [comment]
Simplify becomes enabled whenever an operand is negative. 

Unfortunately there isn't a singular term for this, and while "simplify signs" might be more accurate it is verbose. We used a symbolic representation for this in Expression Exchange, but it was too large for this region in the sim. Simplify can mean evaluate, that is true, but our '=' button does that. 

We did show the sim to teachers and they didn't bring up concern with the term "simplify", and students did figure it out in interviews. So while I agree that it's not great terminology, it doesn't seem to be causing harm.
