### ISSUE TITLE
Showing some accordion box titles might improve usability

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#44]
Noted during #35 code review.

I'm sure this has been discussed... But I'm wondering why you chose to hide accordion box titles in the Operations and Generic screens.  You appear to have the space to show titles, and it would clarify what it is you're setting in those accordion boxes. 

For example, the initial state of the Operations screen looks like this:

<img width="1023" alt="screenshot_795" src="https://user-images.githubusercontent.com/3046552/103158654-30320280-477d-11eb-830c-9503051c79ba.png">

It's clear that the bottom accordion box is allowing me to change my initial new worth.  But unless I collapse the top accordion box, I'm not going to know that what I'm changing in that accordion box is my current "Net Worth".

Then I move on to the Generic screen.  The accordion box looks identical to the Operations screen, so I may think I'm still setting "Net Worth".  Unless I collapse this accordion box, I'm not going to discover that I'm modifying a more generic "Numerical Expression".

**Comment by pixelzoom** [comment]
Imo, accordion box titles should generally be shown.  It shouldn't be a subjective/aesthetic choice, and there are 2 situations that justify hiding the title:

(1) Vertical space is constrained, and you have no other choice. And in this situation, you should strive to communicate the title via the content.
(2) Wording in the title and in the content is nearly identical, so the title is redundant.

The cases I mentioned in this sim don't seem to fit either of those situations.

**Comment by amanda-phet** [comment]
I think this is a good idea for the Operations screen, because knowing that the top is "net worth" is critical information that could get lost. I don't recall it being an issue in interviews because most students got here immediately after playing on Net Worth, but I don't see any downside to including that information to be clear we're still in the net worth context. 

However we are a bit limited on vertical space because of the operation description... so we'll need to see how tall it makes this accordion box. 

I would not add a title for Generic, because "numerical description" is pretty verbose, and not important information at all.

**Comment by amanda-phet** [comment]
Meeting 1/7/21: 

We want to try adding a title to the accordion box on the Operations screen: Net Worth ($). 

Also, shift the number line and initial net worth down a bit.

**Comment by jbphet** [comment]
I've done one round of changes for this, and we should review in the next design meeting.

**Comment by amanda-phet** [comment]
These changes look good to me.
