### ISSUE TITLE
Color-code pickers to match the thing that they are changing.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#46]
PhET typically color-codes pickers to match the thing that they are changing.  This sim does not do that - all of the pickers are the default 'black'. Any reason why?  Examples below.

Operations screen, point that represents "Initial Net Worth"
<img width="413" alt="screenshot_798" src="https://user-images.githubusercontent.com/3046552/103158895-31186380-4780-11eb-99cb-24934a2275f6.png">

Operations and Generic screens, point that was added via operation control:

<img width="295" alt="screenshot_799" src="https://user-images.githubusercontent.com/3046552/103158911-54431300-4780-11eb-85cc-901986a2384c.png">

**Comment by amanda-phet** [comment]
Related to https://github.com/phetsims/number-line-operations/issues/42 

This might be a lot of blue if we make this change in the carousel, but I'd like to try it out.

**Comment by amanda-phet** [comment]
We noticed that the actual operation **is** black, and if we color-code the pickers to match the points, that could look out of sync, because the blue point would have a value that is likely different from the value in the picker. 

However, the initial net worth is directly controlling the point, so it would make sense to color-code that one to match the dark blue point.

**Comment by jbphet** [comment]
I've added color for the initial net worth picker.  @amanda-phet - please take a look on master and, if it looks good to you, I think we can just close this one.  I'm good with it.

**Comment by amanda-phet** [comment]
Looks good to me. Thanks!
