### ISSUE TITLE
NumberLinePoint dispose calls non-existent super.dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#58]
Related to #35 code review.

In NumberLinePoint.js:

```js
  /**
   * release all memory to avoid leaks
   * @public
   * @override
   */
  dispose() {
    this.disposeEmitterNumberLinePoint.emit();
    super.dispose();
  }
```

NumberLinePoint does not extend any class, so the call to `super.dispose()` here should fail.  So I suspect that either (a) NumberLinePoint instances exist for the lifetime of the sim and this method can be removed, or (b) NumberLinePoint `dispose` is not being called and the sim has a memory leak.  

Labeling as "blocks sim publication", since this issue has implications that are potentially serious, and it affects the entire suite.

**Comment by jbphet** [comment]
In number-line-operations, there are no calls to the dispose function, since all points are created up from and added to and removed from the number line as operations come and go.  That's why this issue wasn't hit.

However, there were definitely some missing dispose calls in number-line-integers.  I've addressed those.

**Comment by jbphet** [comment]
And one in number-line-distance too.

**Comment by jbphet** [comment]
Oh, and I've removed the call to the non-existent `super.dispose()` call.

**Comment by jbphet** [comment]
I've manually and fuzz tested all sims in the suite and things look good.  I'll do another memory test on NLO before publication, so I think it's safe to close this.
