### ISSUE TITLE
Assertion failed: did not find press

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#70]
For https://github.com/phetsims/QA/issues/593. Found on Win 10 Chrome while running a fuzz test on the debug build.
This happened when I clicked using the mouse to stop the audio context warning. The page zoomed in a bit because of this. The sim and fuzzing did not seem to stop, but the assertion came up. It does not seem to happen every time.
<img width="959" alt="inputduringfuzz" src="https://user-images.githubusercontent.com/41024075/103589841-98819200-4ea9-11eb-9aec-8447fda1d60d.png">

**Comment by jbphet** [comment]
I'm able to make this happen on master pretty easily by doing a few quick click-drag-release actions with the mouse.  I tried the same test on Natural Selection, and it happens there too.

I've got a stack trace pasted below.  I've looked it over, but I'm not sure who to assign it to, so I'm going to assign it to @jonathanolson for his expertise in Scenery events, @jessegreenberg because it seems like it could be related to pinch-and-zoom, and @zepumph since `phetioPlayback ` is in the stack and I don't know why.  I'll mark for dev meeting and we can perhaps sort it out a bit more.

```
window.assertions.assertFunction (assert.js:23)
findPress (MultiListener.js:235)
move (MultiListener.js:198)
dispatchToListeners (Input.js:1825)
dispatchEvent (Input.js:1779)
branchChangeEvents (Input.js:1681)
moveEvent (Input.js:1616)
Input.mouseMoveAction.Action.phetioPlayback (Input.js:322)
execute (Action.js:225)
mouseMove (Input.js:1128)
pointerMove (Input.js:1435)
run (BatchedDOMEvent.js:64)
fireBatchedEvents (Input.js:823)
batchEvent (Input.js:784)
batchWindowEvent (BrowserEvents.js:321)
onpointermove (BrowserEvents.js:374)
```

**Comment by zepumph** [comment]
This is a duplicate/sim-specific version of https://github.com/phetsims/scenery/issues/1128.

**Comment by jessegreenberg** [comment]
Thanks, yes this has been fixed in https://github.com/phetsims/scenery/issues/1128. Closing.
