### ISSUE TITLE
Artwork for Net Worth screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#8]
@jbphet and I decided to use different artwork for the assets and debts for when they are in the bags (smaller and don't have a value on them) and outside of the bag (have a value generated in the code). I also added a tag to each bag for the Assets and Debts labels. So here is the new artwork, and mockups to jog our memory. 

## Items in panels:
![image](https://user-images.githubusercontent.com/7852916/82266853-0a5f9800-9928-11ea-8980-14535ea6b7c9.png)

### Artwork: (values added programmatically) 
[panel artwork.zip](https://github.com/phetsims/number-line-operations/files/4647324/panel.artwork.zip)

![debt-100-value](https://user-images.githubusercontent.com/7852916/82267126-be612300-9928-11ea-8d99-64b0de866319.png)
![debt-200-value](https://user-images.githubusercontent.com/7852916/82267127-bef9b980-9928-11ea-8681-100fbf0bffcc.png)
![debt-300-value](https://user-images.githubusercontent.com/7852916/82267128-bef9b980-9928-11ea-8439-5cd3c68f6d74.png)
![debt-400-value](https://user-images.githubusercontent.com/7852916/82267129-bf925000-9928-11ea-8960-19988d0ba8a0.png)
![asset-400-value](https://user-images.githubusercontent.com/7852916/82267154-c8832180-9928-11ea-9786-bc9e07ebdb4e.png)
![asset-300-value](https://user-images.githubusercontent.com/7852916/82267155-c8832180-9928-11ea-8837-caeec438cdec.png)
![asset-200-value](https://user-images.githubusercontent.com/7852916/82267157-c91bb800-9928-11ea-9b3a-1bdd4e132765.png)
![asset-100-value](https://user-images.githubusercontent.com/7852916/82267158-c91bb800-9928-11ea-9ff5-c72524975798.png)

## Items in bags: 
![image](https://user-images.githubusercontent.com/7852916/82266931-472b8f00-9928-11ea-94b4-09886609bd3c.png)

### Artwork: 
[bag artwork.zip](https://github.com/phetsims/number-line-operations/files/4647322/bag.artwork.zip)

![debt-400](https://user-images.githubusercontent.com/7852916/82267286-1730bb80-9929-11ea-9548-09c395ea67f1.png)
![debt-300](https://user-images.githubusercontent.com/7852916/82267287-1730bb80-9929-11ea-80bb-9a6c4897ffcd.png)
![debt-200](https://user-images.githubusercontent.com/7852916/82267288-17c95200-9929-11ea-89f5-6901e104105d.png)
![debt-100](https://user-images.githubusercontent.com/7852916/82267289-17c95200-9929-11ea-8fb7-5d04286c38a6.png)
![asset-400](https://user-images.githubusercontent.com/7852916/82267294-1a2bac00-9929-11ea-92cd-fcd4a0fc3d2c.png)
![asset-300](https://user-images.githubusercontent.com/7852916/82267295-1ac44280-9929-11ea-80d5-9366a9220bf6.png)
![asset-200](https://user-images.githubusercontent.com/7852916/82267296-1ac44280-9929-11ea-94cf-7ac2e5bb9bec.png)
![asset-100](https://user-images.githubusercontent.com/7852916/82267297-1ac44280-9929-11ea-8b9b-4d5e8a76c8fd.png)

## Bags: (tag added programmatically) 
[money bags.zip](https://github.com/phetsims/number-line-operations/files/4647328/money.bags.zip)

![debts-bag](https://user-images.githubusercontent.com/7852916/82267376-64ad2880-9929-11ea-9436-66af8f23b74e.png)
![assets-bag](https://user-images.githubusercontent.com/7852916/82267377-65de5580-9929-11ea-9ea6-5484bb954717.png)

**Comment by jbphet** [comment]
@amanda-phet - I've integrated the artwork, please have a look on master and let me know if you think any adjustments are needed.  I have one specific question: I did the tags a little differently than they appear in the mockup - I made the text centered in the tag rather than offset.  I did this because it was quicker, but I can match the mockup if you think it would look better.  Your call.

**Comment by amanda-phet** [comment]
Based on feedback from teachers, I've added numerals to the credit cards to make them look more like credit cards, as well as a TV instead of a gold bar. 

Here is the new artwork, when you are ready to integrate it. I will commit the new ai file, but leave these to you so you can run `grunt modify` and verify that they are all correct. 

For the TV, since it's new, you can put me for the credits. 

![asset-200-value](https://user-images.githubusercontent.com/7852916/88245086-1252f580-cc53-11ea-9440-04964f9a38c3.png)
![asset-200](https://user-images.githubusercontent.com/7852916/88245088-12eb8c00-cc53-11ea-954f-65962d79d9c4.png)

![debt-200-value](https://user-images.githubusercontent.com/7852916/88245093-1848d680-cc53-11ea-870e-9da8fe3f57fe.png)
![debt-200](https://user-images.githubusercontent.com/7852916/88245094-1848d680-cc53-11ea-9488-254ef2a474a1.png)

![debt-400-value](https://user-images.githubusercontent.com/7852916/88245097-1c74f400-cc53-11ea-8ed6-33d3c20ba534.png)
![debt-400](https://user-images.githubusercontent.com/7852916/88245098-1c74f400-cc53-11ea-8b0d-c2ef678c13db.png)

**Comment by jbphet** [comment]
The most recent round of artwork has been integrated.  @amanda-phet - please review https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.9/phet/number-line-operations_en_phet.html and let me know if anything needs to change for this.

The next step for the artwork should be to get versions of the loan icons that don't have the word "loan" so that we can make this translatable.

**Comment by amanda-phet** [comment]
All of the artwork seemed recognizable by students in interviews- yay! It all looks great to me. 

Here is the loan artwork without the text. Can you try to match what I had, using an italic Times font? 

![asset-debt-artwork_debt-100-value](https://user-images.githubusercontent.com/7852916/91097087-52274700-e61c-11ea-9cb3-d7ed29c992fb.png)
![asset-debt-artwork_debt-100](https://user-images.githubusercontent.com/7852916/91097088-52bfdd80-e61c-11ea-952f-023a18504caf.png)
![asset-debt-artwork_debt-300-value](https://user-images.githubusercontent.com/7852916/91097091-52bfdd80-e61c-11ea-8fc9-4c721b2b4db8.png)
![asset-debt-artwork_debt-300](https://user-images.githubusercontent.com/7852916/91097092-53587400-e61c-11ea-81bd-c1bcb85248c3.png)

**Comment by jbphet** [comment]
This artwork is integrated, but I have one suggestion: The assets bag has this sort of "wrinkle line" that extends down into the bag, and I feel like it looks weird if the items that are in the bag go over it, since they are conceptually supposed to be _in_ the bag, not on it.  I initially positioned the assets to be below this, but it's nice to have the assets sit a little higher in the bag so that they have more space.  See the screenshot below for a visual example.  Can that wrinkle be taken off or reduced in size?

![image](https://user-images.githubusercontent.com/3082831/91366197-52604780-e7c0-11ea-8a6d-be4eef774c6a.png)

**Comment by amanda-phet** [comment]
@jbphet I updated the assets-bag.png artwork wit ha smaller wrinkle. I think it should work, but can you do that image thing you need to do so that I can check in master?

**Comment by jbphet** [comment]
Okay, I think all the latest artwork has been integrated.  Closing.
